services:
  - type: web
    name: pediaca
    runtime: python
    buildCommand: apt-get install -y fonts-dejavu-core fonts-liberation && pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
